// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rvofzcykgemizjbvltnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2b2Z6Y3lrZ2VtaXpqYnZsdG52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2NTEwMjQsImV4cCI6MjA1NzIyNzAyNH0.xSfMWNmqa9eg2i7ISL2kVzAJyLRF9iYOFd30dxGEdzM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);